//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aboneler
    {
        public int aboneId { get; set; }
        public int operatorId { get; set; }
        public int tipId { get; set; }
        public string telefon { get; set; }
        public string tc { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public int cinsiyetId { get; set; }
        public string ilksoyadi { get; set; }
        public string anaAdi { get; set; }
        public string babaAdi { get; set; }
        public string dogumYeri { get; set; }
        public Nullable<System.DateTime> dogumtarihi { get; set; }
        public int nufusilId { get; set; }
        public int nufusilceId { get; set; }
        public int adresIlId { get; set; }
        public int adresIlceId { get; set; }
        public int adresMahalleId { get; set; }
        public int adresCaddeSokakId { get; set; }
        public string adresKapiNo { get; set; }
        public string adresDaire { get; set; }
        public Nullable<int> Tedas { get; set; }
        public Nullable<int> Blacklst { get; set; }
        public Nullable<int> aktarim { get; set; }
        public Nullable<int> tempid { get; set; }
    }
}
