//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caddeler
    {
        public int caddeId { get; set; }
        public string caddeAdi { get; set; }
        public int mahalleId { get; set; }
    
        public virtual Mahalle Mahalle { get; set; }
    }
}
