//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MYPORTALEntities : DbContext
    {
        public MYPORTALEntities()
            : base("name=MYPORTALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Caddeler> Caddeler { get; set; }
        public virtual DbSet<Cinsiyet> Cinsiyet { get; set; }
        public virtual DbSet<Ilceler> Ilceler { get; set; }
        public virtual DbSet<Kayitlar> Kayitlar { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<LogDokum> LogDokum { get; set; }
        public virtual DbSet<LogKullanici> LogKullanici { get; set; }
        public virtual DbSet<Mahalle> Mahalle { get; set; }
        public virtual DbSet<sehirler> sehirler { get; set; }
        public virtual DbSet<LogGirisCikis> LogGirisCikis { get; set; }
    
        public virtual ObjectResult<prAdSoyadBul_Result> prAdSoyadBul(string adi, string soyadi, string ilAdi, string ilceAdi)
        {
            var adiParameter = adi != null ?
                new ObjectParameter("Adi", adi) :
                new ObjectParameter("Adi", typeof(string));
    
            var soyadiParameter = soyadi != null ?
                new ObjectParameter("Soyadi", soyadi) :
                new ObjectParameter("Soyadi", typeof(string));
    
            var ilAdiParameter = ilAdi != null ?
                new ObjectParameter("IlAdi", ilAdi) :
                new ObjectParameter("IlAdi", typeof(string));
    
            var ilceAdiParameter = ilceAdi != null ?
                new ObjectParameter("IlceAdi", ilceAdi) :
                new ObjectParameter("IlceAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prAdSoyadBul_Result>("prAdSoyadBul", adiParameter, soyadiParameter, ilAdiParameter, ilceAdiParameter);
        }
    
        public virtual ObjectResult<prTelefonBul_Result> prTelefonBul(string telefon)
        {
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prTelefonBul_Result>("prTelefonBul", telefonParameter);
        }
    
        public virtual ObjectResult<string> prIlce(string sehirAdi)
        {
            var sehirAdiParameter = sehirAdi != null ?
                new ObjectParameter("SehirAdi", sehirAdi) :
                new ObjectParameter("SehirAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("prIlce", sehirAdiParameter);
        }
    
        public virtual ObjectResult<string> prMahalle(string sehirAdi, string ilceAdi)
        {
            var sehirAdiParameter = sehirAdi != null ?
                new ObjectParameter("SehirAdi", sehirAdi) :
                new ObjectParameter("SehirAdi", typeof(string));
    
            var ilceAdiParameter = ilceAdi != null ?
                new ObjectParameter("IlceAdi", ilceAdi) :
                new ObjectParameter("IlceAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("prMahalle", sehirAdiParameter, ilceAdiParameter);
        }
    
        public virtual ObjectResult<string> prIlceler(string sehirAdi)
        {
            var sehirAdiParameter = sehirAdi != null ?
                new ObjectParameter("SehirAdi", sehirAdi) :
                new ObjectParameter("SehirAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("prIlceler", sehirAdiParameter);
        }
    }
}
