//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayitlar
    {
        public int Id { get; set; }
        public string Telefon { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Cinsiyet { get; set; }
        public string DogumYeri { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Nufusil { get; set; }
        public string Nufusilce { get; set; }
        public string Adresil { get; set; }
        public string Adresilce { get; set; }
        public string AdresBelde { get; set; }
        public string AdresMahalle { get; set; }
        public string AdresCaddeSokak { get; set; }
        public string AdresKapiNo { get; set; }
        public string AdresDaire { get; set; }
        public bool KaraListe { get; set; }
        public Nullable<int> Yas { get; set; }
    }
}
