//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int Id { get; set; }
        public string Seviye { get; set; }
        public string KulAdi { get; set; }
        public string KulSifre { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<bool> TCSorgulasin { get; set; }
        public Nullable<bool> DokumAlabilsin { get; set; }
        public Nullable<bool> AdSoyadSorgulasin { get; set; }
        public string Ekleyen { get; set; }
        public Nullable<System.DateTime> EklemeTar { get; set; }
        public string Duzenleyen { get; set; }
        public Nullable<System.DateTime> DuzenlemeTar { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<System.DateTime> SonGirisTar { get; set; }
    }
}
