//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogDokum
    {
        public int Id { get; set; }
        public string KulAdi { get; set; }
        public string EkranAdi { get; set; }
        public Nullable<int> Adet { get; set; }
    }
}
