//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mahalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mahalle()
        {
            this.Caddeler = new HashSet<Caddeler>();
        }
    
        public int mahalleId { get; set; }
        public string mahalleAdi { get; set; }
        public int ilceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caddeler> Caddeler { get; set; }
        public virtual Ilceler Ilceler { get; set; }
    }
}
